# Generated by Django 5.2.5 on 2026-06-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0005_brand_notification_email'),
        ('offer', '0034_advertiser_archive_state'),
        ('user_profile', '0008_profile_archive_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('AFFILIATE', 'Affiliate'), ('ADVERTISER', 'Advertiser')], max_length=10)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('source', models.CharField(default='self-registration', max_length=64)),
                ('pipeline_stage', models.CharField(choices=[('NEW', 'New'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('ACTIVATED', 'Activated'), ('DORMANT', 'Dormant')], default='NEW', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='offer.advertiser')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='brands.brand')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='user_profile.profile')),
            ],
            options={
                'ordering': ('-last_activity_at', '-created_at'),
                'indexes': [models.Index(fields=['brand', 'pipeline_stage'], name='leads_lead_brand_i_705f87_idx'), models.Index(fields=['lead_type'], name='leads_lead_lead_ty_f6ba1c_idx')],
            },
        ),
    ]
