# Generated by Django 5.2.5 on 2026-06-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_default_brand_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='smtp_from_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='brand',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='brand',
            name='smtp_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='brand',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='brand',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
