# Generated by Django 5.2.5 on 2026-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_brand_archive_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
