# Generated by Django 5.2.5 on 2026-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brand_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='owner_sales_notification_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
