"""Idempotent demo/integration seed for the ChainPulse tenant.

Why this exists: ChainPulse is reachable but empty — no offers, no affiliates —
so every submission returns "offer_id does not resolve to an offer you can send
to" and the integrator cannot get a green end-to-end run. This provisions the
minimum a real integration test needs.

SAFETY
------
* Refuses to run when DEBUG is False unless --force is passed, so it cannot be
  invoked casually against a production-like environment.
* Never hard-codes a key. The API key is generated by APIKey.generate() and its
  secret is printed ONCE to stdout — the same show-once contract the affiliate
  UI uses. Nothing secret is written to the repo.
* Idempotent by natural key (brand slug, offer title, username): re-running
  updates in place and creates no duplicates. Re-running does NOT rotate the
  API key unless --rotate-key is passed, so a working integration is not broken
  by an accidental second run.
"""
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from brands.models import Brand
from offer.models import Advertiser, Offer
from public_api.models import APIKey
from user_profile.models import Profile

BRAND_SLUG = 'chainpulse'
BRAND_NAME = 'ChainPulse'
PRIMARY_DOMAIN = 'app.trackingplatform.guru'
TRACKING_DOMAIN = 'track.trackingplatform.guru'

ADVERTISER_COMPANY = 'ChainPulse Demo Advertiser'
ADVERTISER_EMAIL = 'demo-advertiser@chainpulse.invalid'
OFFER_TITLE = 'ChainPulse Demo Offer'
AFFILIATE_USERNAME = 'chainpulse_demo_affiliate'
AFFILIATE_EMAIL = 'demo-affiliate@chainpulse.invalid'
KEY_NAME = 'ChainPulse integration key'

User = get_user_model()


class Command(BaseCommand):
    help = 'Idempotently provision the ChainPulse tenant with an offer, an affiliate and an API key.'

    def add_arguments(self, parser):
        parser.add_argument(
            '--force', action='store_true',
            help='Required to run when DEBUG is False (production-like).')
        parser.add_argument(
            '--rotate-key', action='store_true',
            help='Regenerate the API key secret. Off by default so a re-run does '
                 'not break a working integration.')

    def handle(self, *args, **options):
        if not settings.DEBUG and not options['force']:
            raise CommandError(
                'DEBUG is False — this looks production-like. Re-run with --force '
                'if you really mean to seed demo data here.')

        with transaction.atomic():
            brand, brand_created = Brand.objects.update_or_create(
                slug=BRAND_SLUG,
                defaults=dict(
                    name=BRAND_NAME,
                    primary_domain=PRIMARY_DOMAIN,
                    tracking_domain=TRACKING_DOMAIN,
                    is_default=False,
                    is_archived=False,
                ),
            )

            adv_user, _ = User.objects.get_or_create(
                username=f'{AFFILIATE_USERNAME}_advertiser',
                defaults={'email': ADVERTISER_EMAIL},
            )
            advertiser, _ = Advertiser.objects.update_or_create(
                user=adv_user,
                defaults=dict(
                    brand=brand,
                    company=ADVERTISER_COMPANY,
                    email=ADVERTISER_EMAIL,
                    # Both required for the offer to pass offers_for_affiliate's
                    # advertiser gate — a PENDING advertiser's offers are hidden.
                    advertiser_status=Advertiser.AdvertiserStatus.APPROVED,
                    email_verified=True,
                    is_archived=False,
                ),
            )

            offer, offer_created = Offer.objects.update_or_create(
                title=OFFER_TITLE,
                defaults=dict(
                    brand=brand,
                    advertiser=advertiser,
                    tracking_link=f'https://{TRACKING_DOMAIN}/click',
                    status='Active',
                ),
            )

            affiliate, aff_created = User.objects.get_or_create(
                username=AFFILIATE_USERNAME,
                defaults={'email': AFFILIATE_EMAIL},
            )
            profile = affiliate.profile
            profile.role = Profile.Role.AFFILIATE
            profile.affiliate_status = Profile.AffiliateStatus.APPROVED
            profile.email_verified = True
            profile.brand = brand
            profile.save()

            key = APIKey.objects.filter(user=affiliate, name=KEY_NAME, is_active=True).first()
            if key is None:
                key = APIKey.generate(user=affiliate, name=KEY_NAME, requests_per_hour=1000)
                secret = key.secret
                key_note = 'created'
            elif options['rotate_key']:
                secret = key.regenerate_secret()
                key_note = 'rotated'
            else:
                secret = None
                key_note = 'existing (pass --rotate-key to regenerate)'

        w = self.stdout.write
        w(self.style.SUCCESS('ChainPulse seed complete.'))
        w(f'  brand      : {brand.name} ({brand.slug}) '
          f'{"created" if brand_created else "updated"} — https://{brand.primary_domain}')
        w(f'  advertiser : {advertiser.company} [APPROVED, verified]')
        w(f'  offer      : "{offer.title}" offer_id={offer.pk} '
          f'{"created" if offer_created else "updated"} [Active]')
        w(f'  affiliate  : {affiliate.username} '
          f'{"created" if aff_created else "updated"} [APPROVED, brand={brand.slug}]')
        w(f'  api key    : {key_note}')
        if secret:
            w(self.style.WARNING(f'  SECRET (shown once): {secret}'))
        w('')
        w('Smoke test:')
        w(f'  curl -X POST https://{brand.primary_domain}/api/leads/submit \\')
        w('    -H "Authorization: ApiKey <secret>" -H "Content-Type: application/json" \\')
        w(f'    -d \'{{"email":"t@example.com","phone":"+15551234567","offer_id":{offer.pk}}}\'')
