# Generated by Django 5.2.5 on 2026-07-29 06:48

import user_profile.geo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0034_advertiser_archive_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='country',
            field=models.CharField(blank=True, choices=user_profile.geo.country_choices, default='', max_length=2),
        ),
    ]
