# Generated by Django 5.2.5 on 2026-06-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0034_advertiser_archive_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('SOLO', 'Solo affiliate / publisher'), ('ADVERTISER', 'Advertiser / brand running offers'), ('NETWORK', 'Network / agency wanting a white-label platform'), ('OTHER', 'Other')], max_length=12)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('scale', models.CharField(blank=True, default='', help_text='Monthly volume / scale — clicks or conversions per month, or affiliate count for networks.', max_length=255)),
                ('pain', models.TextField(blank=True, default='', help_text='Current pain / why looking.')),
                ('timeline', models.CharField(blank=True, choices=[('NOW', 'Now'), ('SOON', '1–3 months'), ('EXPLORING', 'Just exploring')], default='', max_length=10)),
                ('budget', models.CharField(blank=True, default='', max_length=120)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('sales_stage', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('DEMO_PROPOSAL', 'Demo / proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('traffic_sources', models.ManyToManyField(blank=True, related_name='platform_leads', to='offer.trafficsource')),
                ('verticals', models.ManyToManyField(blank=True, related_name='platform_leads', to='offer.category')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sales_stage'], name='platform_le_sales_s_e81449_idx'), models.Index(fields=['lead_type'], name='platform_le_lead_ty_73aa18_idx')],
            },
        ),
    ]
