# Generated by Django 5.2.5 on 2026-06-06 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_owner_sales_notification_email'),
        ('platform_leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformlead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformlead',
            name='converted_brand',
            field=models.ForeignKey(blank=True, help_text='The Brand this WON lead was converted into, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_leads', to='brands.brand'),
        ),
    ]
