"""ISO-4217 world currencies — single source for the offer.Currency table.

Each entry is (code, name, symbol). Used by the data migration that seeds the
``offer.Currency`` table and by ``currency_choices`` for dropdowns. Codes follow
ISO-4217 alpha-3.
"""

# (code, name, symbol)
ISO_4217_CURRENCIES = [
    ('AED', 'UAE Dirham', 'د.إ'),
    ('AFN', 'Afghan Afghani', '؋'),
    ('ALL', 'Albanian Lek', 'L'),
    ('AMD', 'Armenian Dram', '֏'),
    ('ANG', 'Netherlands Antillean Guilder', 'ƒ'),
    ('AOA', 'Angolan Kwanza', 'Kz'),
    ('ARS', 'Argentine Peso', '$'),
    ('AUD', 'Australian Dollar', '$'),
    ('AWG', 'Aruban Florin', 'ƒ'),
    ('AZN', 'Azerbaijani Manat', '₼'),
    ('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM'),
    ('BBD', 'Barbadian Dollar', '$'),
    ('BDT', 'Bangladeshi Taka', '৳'),
    ('BGN', 'Bulgarian Lev', 'лв'),
    ('BHD', 'Bahraini Dinar', '.د.ب'),
    ('BIF', 'Burundian Franc', 'FBu'),
    ('BMD', 'Bermudan Dollar', '$'),
    ('BND', 'Brunei Dollar', '$'),
    ('BOB', 'Bolivian Boliviano', 'Bs.'),
    ('BRL', 'Brazilian Real', 'R$'),
    ('BSD', 'Bahamian Dollar', '$'),
    ('BTN', 'Bhutanese Ngultrum', 'Nu.'),
    ('BWP', 'Botswanan Pula', 'P'),
    ('BYN', 'Belarusian Ruble', 'Br'),
    ('BZD', 'Belize Dollar', 'BZ$'),
    ('CAD', 'Canadian Dollar', '$'),
    ('CDF', 'Congolese Franc', 'FC'),
    ('CHF', 'Swiss Franc', 'CHF'),
    ('CLP', 'Chilean Peso', '$'),
    ('CNY', 'Chinese Yuan', '¥'),
    ('COP', 'Colombian Peso', '$'),
    ('CRC', 'Costa Rican Colón', '₡'),
    ('CUP', 'Cuban Peso', '$'),
    ('CVE', 'Cape Verdean Escudo', '$'),
    ('CZK', 'Czech Koruna', 'Kč'),
    ('DJF', 'Djiboutian Franc', 'Fdj'),
    ('DKK', 'Danish Krone', 'kr'),
    ('DOP', 'Dominican Peso', 'RD$'),
    ('DZD', 'Algerian Dinar', 'دج'),
    ('EGP', 'Egyptian Pound', '£'),
    ('ERN', 'Eritrean Nakfa', 'Nfk'),
    ('ETB', 'Ethiopian Birr', 'Br'),
    ('EUR', 'Euro', '€'),
    ('FJD', 'Fijian Dollar', '$'),
    ('FKP', 'Falkland Islands Pound', '£'),
    ('GBP', 'British Pound Sterling', '£'),
    ('GEL', 'Georgian Lari', '₾'),
    ('GHS', 'Ghanaian Cedi', '₵'),
    ('GIP', 'Gibraltar Pound', '£'),
    ('GMD', 'Gambian Dalasi', 'D'),
    ('GNF', 'Guinean Franc', 'FG'),
    ('GTQ', 'Guatemalan Quetzal', 'Q'),
    ('GYD', 'Guyanaese Dollar', '$'),
    ('HKD', 'Hong Kong Dollar', 'HK$'),
    ('HNL', 'Honduran Lempira', 'L'),
    ('HRK', 'Croatian Kuna', 'kn'),
    ('HTG', 'Haitian Gourde', 'G'),
    ('HUF', 'Hungarian Forint', 'Ft'),
    ('IDR', 'Indonesian Rupiah', 'Rp'),
    ('ILS', 'Israeli New Shekel', '₪'),
    ('INR', 'Indian Rupee', '₹'),
    ('IQD', 'Iraqi Dinar', 'ع.د'),
    ('IRR', 'Iranian Rial', '﷼'),
    ('ISK', 'Icelandic Króna', 'kr'),
    ('JMD', 'Jamaican Dollar', 'J$'),
    ('JOD', 'Jordanian Dinar', 'د.ا'),
    ('JPY', 'Japanese Yen', '¥'),
    ('KES', 'Kenyan Shilling', 'KSh'),
    ('KGS', 'Kyrgystani Som', 'лв'),
    ('KHR', 'Cambodian Riel', '៛'),
    ('KMF', 'Comorian Franc', 'CF'),
    ('KPW', 'North Korean Won', '₩'),
    ('KRW', 'South Korean Won', '₩'),
    ('KWD', 'Kuwaiti Dinar', 'د.ك'),
    ('KYD', 'Cayman Islands Dollar', '$'),
    ('KZT', 'Kazakhstani Tenge', '₸'),
    ('LAK', 'Laotian Kip', '₭'),
    ('LBP', 'Lebanese Pound', 'ل.ل'),
    ('LKR', 'Sri Lankan Rupee', 'Rs'),
    ('LRD', 'Liberian Dollar', '$'),
    ('LSL', 'Lesotho Loti', 'L'),
    ('LYD', 'Libyan Dinar', 'ل.د'),
    ('MAD', 'Moroccan Dirham', 'د.م.'),
    ('MDL', 'Moldovan Leu', 'L'),
    ('MGA', 'Malagasy Ariary', 'Ar'),
    ('MKD', 'Macedonian Denar', 'ден'),
    ('MMK', 'Myanmar Kyat', 'K'),
    ('MNT', 'Mongolian Tugrik', '₮'),
    ('MOP', 'Macanese Pataca', 'MOP$'),
    ('MRU', 'Mauritanian Ouguiya', 'UM'),
    ('MUR', 'Mauritian Rupee', '₨'),
    ('MVR', 'Maldivian Rufiyaa', 'Rf'),
    ('MWK', 'Malawian Kwacha', 'MK'),
    ('MXN', 'Mexican Peso', '$'),
    ('MYR', 'Malaysian Ringgit', 'RM'),
    ('MZN', 'Mozambican Metical', 'MT'),
    ('NAD', 'Namibian Dollar', '$'),
    ('NGN', 'Nigerian Naira', '₦'),
    ('NIO', 'Nicaraguan Córdoba', 'C$'),
    ('NOK', 'Norwegian Krone', 'kr'),
    ('NPR', 'Nepalese Rupee', '₨'),
    ('NZD', 'New Zealand Dollar', '$'),
    ('OMR', 'Omani Rial', 'ر.ع.'),
    ('PAB', 'Panamanian Balboa', 'B/.'),
    ('PEN', 'Peruvian Sol', 'S/.'),
    ('PGK', 'Papua New Guinean Kina', 'K'),
    ('PHP', 'Philippine Peso', '₱'),
    ('PKR', 'Pakistani Rupee', '₨'),
    ('PLN', 'Polish Zloty', 'zł'),
    ('PYG', 'Paraguayan Guarani', '₲'),
    ('QAR', 'Qatari Rial', 'ر.ق'),
    ('RON', 'Romanian Leu', 'lei'),
    ('RSD', 'Serbian Dinar', 'дин.'),
    ('RUB', 'Russian Ruble', '₽'),
    ('RWF', 'Rwandan Franc', 'FRw'),
    ('SAR', 'Saudi Riyal', 'ر.س'),
    ('SBD', 'Solomon Islands Dollar', '$'),
    ('SCR', 'Seychellois Rupee', '₨'),
    ('SDG', 'Sudanese Pound', 'ج.س.'),
    ('SEK', 'Swedish Krona', 'kr'),
    ('SGD', 'Singapore Dollar', 'S$'),
    ('SHP', 'Saint Helena Pound', '£'),
    ('SLE', 'Sierra Leonean Leone', 'Le'),
    ('SOS', 'Somali Shilling', 'S'),
    ('SRD', 'Surinamese Dollar', '$'),
    ('SSP', 'South Sudanese Pound', '£'),
    ('STN', 'São Tomé and Príncipe Dobra', 'Db'),
    ('SYP', 'Syrian Pound', '£'),
    ('SZL', 'Swazi Lilangeni', 'L'),
    ('THB', 'Thai Baht', '฿'),
    ('TJS', 'Tajikistani Somoni', 'ЅМ'),
    ('TMT', 'Turkmenistani Manat', 'm'),
    ('TND', 'Tunisian Dinar', 'د.ت'),
    ('TOP', 'Tongan Paʻanga', 'T$'),
    ('TRY', 'Turkish Lira', '₺'),
    ('TTD', 'Trinidad and Tobago Dollar', 'TT$'),
    ('TWD', 'New Taiwan Dollar', 'NT$'),
    ('TZS', 'Tanzanian Shilling', 'TSh'),
    ('UAH', 'Ukrainian Hryvnia', '₴'),
    ('UGX', 'Ugandan Shilling', 'USh'),
    ('USD', 'US Dollar', '$'),
    ('UYU', 'Uruguayan Peso', '$U'),
    ('UZS', 'Uzbekistan Som', 'лв'),
    ('VES', 'Venezuelan Bolívar', 'Bs.'),
    ('VND', 'Vietnamese Dong', '₫'),
    ('VUV', 'Vanuatu Vatu', 'VT'),
    ('WST', 'Samoan Tala', 'WS$'),
    ('XAF', 'CFA Franc BEAC', 'FCFA'),
    ('XCD', 'East Caribbean Dollar', '$'),
    ('XOF', 'CFA Franc BCEAO', 'CFA'),
    ('XPF', 'CFP Franc', '₣'),
    ('YER', 'Yemeni Rial', '﷼'),
    ('ZAR', 'South African Rand', 'R'),
    ('ZMW', 'Zambian Kwacha', 'ZK'),
    ('ZWL', 'Zimbabwean Dollar', 'Z$'),
]


def currency_choices(include_blank=False):
    """Return [(code, 'CODE — Name'), ...] for form dropdowns, sourced from the
    seeded ``offer.Currency`` table. Falls back to the static ISO-4217 list when
    the table is empty (e.g. fresh test DB)."""
    from offer.models import Currency

    rows = list(Currency.objects.order_by('code').values_list('code', 'name'))
    if not rows:
        rows = [(c[0], c[1]) for c in sorted(ISO_4217_CURRENCIES)]
    choices = [(code, f'{code} — {name}') for code, name in rows]
    if include_blank:
        return [('', '— Select currency —')] + choices
    return choices
