# Generated by Django 5.2.5 on 2026-07-28 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0006_brand_owner_sales_notification_email'),
        ('offer', '0034_advertiser_archive_state'),
        ('tracker', '0016_click_conversion_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_channel', models.CharField(choices=[('affiliate_api', 'Affiliate API'), ('landing_page', 'Landing page')], max_length=20)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=32)),
                ('country_iso2', models.CharField(blank=True, default='', max_length=2)),
                ('vertical', models.CharField(blank=True, default='', help_text="Campaign/vertical tag (the buyer's own 'affiliate' field, e.g. 'crypto') — not a Nexora affiliate.", max_length=120)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('injected', 'Injected'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deposit', 'Deposit')], default='new', max_length=20)),
                ('deposit', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_leads', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_leads', to='brands.brand')),
                ('click', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tracker.click')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_leads', to='offer.offer')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='LeadBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_inject', models.BooleanField(default=False)),
                ('base_url', models.URLField(max_length=500)),
                ('auth_type', models.CharField(choices=[('api_key_query', 'API key in query string'), ('api_key_header', 'API key in header'), ('bearer', 'Bearer token')], default='api_key_query', max_length=20)),
                ('auth_param_name', models.CharField(default='apiKey', max_length=60)),
                ('api_key_encrypted', models.CharField(blank=True, default='', max_length=512)),
                ('single_endpoint_path', models.CharField(default='/leads', max_length=200)),
                ('batch_endpoint_path', models.CharField(blank=True, default='/leads/batch', max_length=200)),
                ('fetch_endpoint_path', models.CharField(blank=True, default='/leads', max_length=200)),
                ('deposits_endpoint_path', models.CharField(blank=True, default='', max_length=200)),
                ('batch_max_size', models.PositiveIntegerField(default=1, help_text='1 disables batching.')),
                ('rate_limit_burst', models.PositiveIntegerField(default=10)),
                ('rate_limit_refill_tokens', models.PositiveIntegerField(default=1)),
                ('rate_limit_refill_seconds', models.PositiveIntegerField(default=1)),
                ('field_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Leave blank for a platform-wide buyer used when a brand has no dedicated one.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_buyers', to='brands.brand')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='LeadInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('duplicate', 'Duplicate (buyer already has this lead)'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='leadgen.leadbuyer')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injections', to='leadgen.lead')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone'], name='leadgen_lea_phone_8a8499_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='leadgen_lea_email_3df532_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leadgen_lea_status_5f9b53_idx'),
        ),
    ]
