# Generated by Django 5.2.5 on 2026-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='buyer_status',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='buyer_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadinjection',
            name='buyer_status',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='leadinjection',
            name='buyer_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
