# Generated by Django 5.2.5 on 2026-07-28 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_owner_sales_notification_email'),
        ('leadgen', '0002_lead_buyer_status_lead_buyer_status_updated_at_and_more'),
        ('offer', '0034_advertiser_archive_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Optional human label, e.g. "US crypto leads -> BuyerX". Purely for your own scanning.', max_length=120)),
                ('country_iso2', models.CharField(blank=True, default='', max_length=2)),
                ('vertical', models.CharField(blank=True, default='', max_length=120)),
                ('source_channel', models.CharField(blank=True, choices=[('affiliate_api', 'Affiliate API'), ('landing_page', 'Landing page'), ('bought', 'Bought traffic')], default='', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text="Lower is tried first among a lead's matching rules.")),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(help_text='Every rule belongs to exactly one brand — no platform-wide routing rule.', on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='brands.brand')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='leadgen.leadbuyer')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to='offer.offer')),
            ],
            options={
                'ordering': ('priority', 'id'),
            },
        ),
    ]
