# Generated by Django 5.2.5 on 2026-07-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0003_routingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadinjection',
            name='chain_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('injected', 'Injected'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deposit', 'Deposit'), ('unrouted', 'Unrouted (chain exhausted)')], default='new', max_length=20),
        ),
    ]
