# Generated by Django 5.2.5 on 2026-07-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0004_leadinjection_chain_managed_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Bump when the platform changes its own API shape, so buyers on an older version of this box do not silently start behaving differently — a version bump is a signal to review them.')),
                ('description', models.TextField(blank=True, default='')),
                ('connector_class', models.CharField(default='leadgen.connectors.LeadBuyerConnector', max_length=200)),
                ('auth_type', models.CharField(choices=[('api_key_query', 'API key in query string'), ('api_key_header', 'API key in header'), ('bearer', 'Bearer token')], default='api_key_query', max_length=20)),
                ('auth_param_name', models.CharField(default='apiKey', max_length=60)),
                ('single_endpoint_path', models.CharField(default='/leads', max_length=200)),
                ('batch_endpoint_path', models.CharField(blank=True, default='/leads/batch', max_length=200)),
                ('fetch_endpoint_path', models.CharField(blank=True, default='/leads', max_length=200)),
                ('deposits_endpoint_path', models.CharField(blank=True, default='', max_length=200)),
                ('batch_max_size', models.PositiveIntegerField(default=1, help_text='1 disables batching.')),
                ('rate_limit_burst', models.PositiveIntegerField(default=10)),
                ('rate_limit_refill_tokens', models.PositiveIntegerField(default=1)),
                ('rate_limit_refill_seconds', models.PositiveIntegerField(default=1)),
                ('default_field_mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='leadbuyer',
            name='box_type',
            field=models.ForeignKey(help_text='Which platform template this buyer speaks. Nullable at the DB level only so the Phase 4 migration stayed additive for the buyer row(s) that predate the Box Registry; always set this.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='leadgen.boxtype'),
        ),
    ]
