# Generated by Django 5.2.5 on 2026-07-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0005_boxtype_leadbuyer_box_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('affiliate_api', 'Affiliate API'), ('landing_page', 'Landing page'), ('bought', 'Bought traffic')], default='', help_text='Restricts this rule to leads from one intake channel; blank matches any. "Bought traffic" has no live intake path yet (leadgen/README.md\'s Phase 6 note) — a rule using it will never match a lead until one exists.', max_length=20),
        ),
    ]
