# Generated by Django 5.2.5 on 2026-07-29 06:48

import user_profile.geo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0006_alter_routingrule_source_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='country_iso2',
            field=models.CharField(blank=True, choices=user_profile.geo.country_choices, default='', max_length=2),
        ),
    ]
