# Generated by Django 5.2.5 on 2026-07-29 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_owner_sales_notification_email'),
        ('leadgen', '0007_alter_routingrule_country_iso2'),
        ('offer', '0035_alter_advertiser_country'),
        ('tracker', '0016_click_conversion_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateOfferLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('testing', 'Testing — Nexora operator sets status'), ('live', 'Live — buyer postback sets status')], default='testing', max_length=10)),
                ('phase_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('test', 'Test'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('rejected', 'Rejected'), ('routed', 'Routed / injected'), ('unrouted', 'Unrouted'), ('failed', 'Failed'), ('pending', 'Pending (with buyer)'), ('no_answer', 'No answer'), ('callback', 'Callback scheduled'), ('wrong_number', 'Wrong / invalid number'), ('not_interested', 'Not interested'), ('do_not_call', 'Do not call'), ('test_ftd', 'Test FTD'), ('ftd', 'FTD (First Time Deposit)'), ('qualified_ftd', 'Qualified FTD / billable'), ('redeposit', 'Redeposit (FTD+)'), ('high_value', 'High value / VIP'), ('approved', 'Approved (billable to affiliate)'), ('chargeback', 'Chargeback / reversed'), ('fraud', 'Fraud'), ('expired', 'Expired')], max_length=20)),
                ('source', models.CharField(choices=[('operator', 'Operator (manual flip)'), ('buyer', 'Buyer postback/sync'), ('system', 'System')], max_length=10)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='The buyer status-sync result or operator form submission that produced this event.')),
                ('phase_at_time', models.CharField(blank=True, default='', help_text='The governing AffiliateOfferLink.phase at the moment this event was recorded (blank when the lead has no affiliate — no phase gating applies).', max_length=10)),
                ('applied', models.BooleanField(default=True)),
                ('override_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='boxtype',
            name='default_status_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('test', 'Test'), ('duplicate', 'Duplicate'), ('invalid', 'Invalid'), ('rejected', 'Rejected'), ('routed', 'Routed / injected'), ('unrouted', 'Unrouted'), ('failed', 'Failed'), ('pending', 'Pending (with buyer)'), ('no_answer', 'No answer'), ('callback', 'Callback scheduled'), ('wrong_number', 'Wrong / invalid number'), ('not_interested', 'Not interested'), ('do_not_call', 'Do not call'), ('test_ftd', 'Test FTD'), ('ftd', 'FTD (First Time Deposit)'), ('qualified_ftd', 'Qualified FTD / billable'), ('redeposit', 'Redeposit (FTD+)'), ('high_value', 'High value / VIP'), ('approved', 'Approved (billable to affiliate)'), ('chargeback', 'Chargeback / reversed'), ('fraud', 'Fraud'), ('expired', 'Expired')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='canonical_status_needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadbuyer',
            name='status_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['canonical_status'], name='leadgen_lea_canonic_5b769d_idx'),
        ),
        migrations.AddField(
            model_name='affiliateofferlink',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliateofferlink',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='offer.offer'),
        ),
        migrations.AddField(
            model_name='affiliateofferlink',
            name='phase_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatusevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Set only for source=operator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatusevent',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='leadgen.lead'),
        ),
        migrations.AddConstraint(
            model_name='affiliateofferlink',
            constraint=models.UniqueConstraint(fields=('affiliate', 'offer'), name='unique_affiliate_offer_link'),
        ),
        migrations.AddIndex(
            model_name='leadstatusevent',
            index=models.Index(fields=['lead', 'created_at'], name='leadgen_lea_lead_id_8dcaff_idx'),
        ),
    ]
