# Generated by Django 5.2.5 on 2026-07-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0008_affiliateofferlink_leadstatusevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
