# Generated by Django 5.2.5 on 2026-07-29 10:56

import django.db.models.deletion
import leadgen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0009_lead_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatusevent',
            name='lead_seq',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AffiliatePostbackConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Macros: {lead_id} {source_id} {status} {status_time} {offer_id} {payout}.', max_length=500)),
                ('secret', models.CharField(default=leadgen.models._generate_postback_secret, help_text='HMAC-SHA256 signing secret (X-Nexora-Signature) — give this to the affiliate once.', max_length=64)),
                ('subscribed_statuses', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postback_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PostbackDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The buyer/affiliate URL actually requested (macros resolved).', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='leadgen.affiliatepostbackconfig')),
                ('status_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postback_deliveries', to='leadgen.leadstatusevent')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
