# Generated by Django 5.2.5 on 2026-08-06 10:27
#
# The routing-waterfall + Hypernet field additions. Every operation below
# adds a column with a default or alters `choices`, so this is metadata-only
# on Postgres: no table rewrite, no backfill, no lock of consequence.
#
# The autodetector also emitted dependencies on brands/offer/AUTH_USER_MODEL
# and an unrelated offer migration for pre-existing model drift in that app.
# Both were removed: no operation here references another app's models, so
# leadgen.0011 is the only real dependency, and this migration must not drag
# an unrelated app's drift along with it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0011_leadbuyer_brand_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='broker_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='leadbuyer',
            name='accepts_overflow',
            field=models.BooleanField(default=False, help_text='May receive leads that a higher-priority buyer in this brand rejected.'),
        ),
        migrations.AddField(
            model_name='leadbuyer',
            name='extra_payload_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('injected', 'Injected'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deposit', 'Deposit'), ('unrouted', 'Unrouted (no buyer configured)'), ('held', 'Held (buyer not auto-injecting)'), ('exhausted', 'Exhausted (all buyers rejected)'), ('quarantined', 'Quarantined (outcome unknown — needs review)')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='routingrule',
            index=models.Index(fields=['brand', 'priority', 'id'], name='leadgen_rule_brand_prio_idx'),
        ),
    ]
