# Generated by Django 5.2.5 on 2026-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0012_lead_broker_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='broker_redirect_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='broker_redirect_url_encrypted',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
