# Generated by Django 5.2.5 on 2026-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0013_lead_broker_redirect_captured_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='leadinjection',
            index=models.Index(condition=models.Q(('next_retry_at__isnull', False)), fields=['status', 'next_retry_at'], name='leadinj_pending_retry_idx'),
        ),
    ]
