# Generated by Django 5.2.5 on 2026-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0014_leadinjection_leadinj_pending_retry_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadbuyer',
            name='extra_credentials_encrypted',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
