# Generated by Django 5.2.5 on 2026-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0015_leadbuyer_extra_credentials_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='language',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
