# Generated by Django 5.2.5 on 2026-08-20 22:10

import offer.verticals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadgen', '0019_boxtype_variable_schema_and_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='vertical',
            field=models.CharField(blank=True, choices=offer.verticals.vertical_choices, default='', max_length=120),
        ),
    ]
