# Generated by Django 5.2.5 on 2026-06-07 05:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_owner_sales_notification_email'),
        ('payouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='control_hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('pending_approval', 'Pending Approval'), ('blocked', 'Blocked'), ('denied', 'Denied'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BrandWithdrawalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_tx_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('per_affiliate_day_count', models.PositiveIntegerField(blank=True, null=True)),
                ('per_affiliate_day_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('per_brand_day_count', models.PositiveIntegerField(blank=True, null=True)),
                ('per_brand_day_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('new_address_cooldown_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('anomaly_multiple', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_control', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand withdrawal control',
                'verbose_name_plural': 'Brand withdrawal controls',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalControlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('per_tx_max', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=14)),
                ('per_affiliate_day_count', models.PositiveIntegerField(default=3)),
                ('per_affiliate_day_amount', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=14)),
                ('per_brand_day_count', models.PositiveIntegerField(default=50)),
                ('per_brand_day_amount', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=16)),
                ('platform_day_count', models.PositiveIntegerField(default=500)),
                ('platform_day_amount', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=18)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=14)),
                ('new_address_cooldown_hours', models.PositiveIntegerField(default=24)),
                ('anomaly_multiple', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Hold a payout larger than this multiple of the affiliate historical average.', max_digits=6)),
                ('anomaly_min_history', models.PositiveIntegerField(default=3, help_text='Minimum past payouts before the multiple rule applies.')),
                ('anomaly_burst_count', models.PositiveIntegerField(default=5, help_text='Hold when this many payout requests appear within the burst window.')),
                ('anomaly_burst_window_minutes', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal control configuration',
                'verbose_name_plural': 'Withdrawal control configuration',
            },
        ),
        migrations.CreateModel(
            name='PayoutDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('blocked_limit', 'Blocked by velocity limit'), ('held_threshold', 'Held for threshold approval'), ('held_cooldown', 'Held for new-address cool-down'), ('held_anomaly', 'Held by anomaly rule'), ('approved', 'Approved by operator'), ('denied', 'Denied by operator'), ('dispatch_failed', 'Dispatch failed')], max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_decisions', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_decisions', to='brands.brand')),
                ('payout_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='payouts.payoutrequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['payout_request', 'created_at'], name='payouts_pay_payout__bd7553_idx'), models.Index(fields=['decision', 'created_at'], name='payouts_pay_decisio_89275b_idx')],
            },
        ),
    ]
