# Generated by Django 5.2.5 on 2026-06-07 12:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0002_withdrawal_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='nowpayments', max_length=32)),
                ('provider_batch_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('currency', models.CharField(default='', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('raw_create_response', models.JSONField(blank=True, default=dict)),
                ('raw_last_status', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Crypto payout batches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='provider_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='provider_withdrawal_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='provider_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_requests', to='payouts.cryptopayoutbatch'),
        ),
        migrations.AddConstraint(
            model_name='payoutrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_withdrawal_id__isnull', False)), fields=('provider_withdrawal_id',), name='payouts_request_unique_provider_withdrawal_id'),
        ),
    ]
