# Generated by Django 5.2.5 on 2026-08-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutologinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(db_index=True, max_length=64, unique=True)),
                ('token_hash', models.CharField(help_text='sha256 of the token string. Never the token itself.', max_length=64)),
                ('scope', models.CharField(help_text='The landing scope the token is bound to. Nothing else is bound.', max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('issued_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('issued_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('expires_at', models.DateTimeField(help_text='Denormalised from the signed token so an operator can read expiry without holding the credential.')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('redeemed_user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autologin_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='AutologinAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('outcome', models.CharField(choices=[('redeemed', 'Redeemed'), ('expired', 'Expired'), ('already_used', 'Already used (replay)'), ('tampered', 'Bad signature / tampered'), ('future_dated', 'Future-dated beyond tolerance'), ('unknown_nonce', 'No issuance record for this nonce'), ('user_unusable', 'Bound user missing or inactive'), ('rate_limited', 'Rate limited'), ('disabled', 'Feature disabled'), ('store_unavailable', 'Nonce/rate store unavailable')], db_index=True, max_length=32)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autologin_attempts', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='sso.autologintoken')),
            ],
            options={
                'ordering': ('-attempted_at',),
            },
        ),
    ]
